name: Deploy source code

on:
  #workflow_dispatch: # for manually run this workflow from the UI.
  #schedule:
  #  - cron: '10 14 * * *' # once a day at 14:10 UTC / at 21:10 BKK
  push:
    branches:
      - main

jobs:
  deploy_source_code:
    name: Deploy source code
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
      - name: Setup databricks CLI
        uses: databricks/setup-cli@main

      - name: List repository on databrick workspace
        run: databricks repos list

      - name: Update databricks repo
        run: databricks repos update /Repos/<path>/<repos_name> --branch <branch_name>
